controller:
  ros__parameters:
    alpha: 0.75
    deadzone: 0.1
    low_pass_filter_enabled: true
    deadzone_enabled: true
    apf_gain: 3.35
    inter_agent_distance: 0.5
    tracked_frame_id: laser
    segments_topic: segments
    instructions_topic: instructions
    detected_objects_topic: detected_objects
    tracking_init_topic: tracking_init
    tracked_objects_topic: tracked_objects
    odometry_topic: scan_odom
    pid_p_gain: 1.0
    pid_i_gain: 0.0
    pid_d_gain: 0.0

tracker:
  ros__parameters:
    detected_objects_topic: detected_objects
    tracked_objects_topic: tracked_objects
    tracking_init_topic: tracking_init
    distance_threshold: 0.2
    disappeared_threshold: 20
    measurement_frequency: 10.0
    kalman_filtering_enabled: False
    
segmentation:
  ros__parameters:
    distance_threshold: 0.05
    max_avg_distance_from_sensor: 1.5
    max_points_segment: 400
    max_segment_width: 0.3
    method_threshold: ''
    min_avg_distance_from_sensor: 0.0
    min_points_segment: 3
    min_segment_width: 0.02
    noise_reduction: 0.3
    restore_defaults: false
    scan_topic: scan
    segmentation_type: jump_distance_merge
    segments_topic: segments
