services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2
    network_mode: host
    devices:
      - /dev/ttyUSB0
    tty: true
    volumes:
      - ./ros2_ws/src/controller/config/tracking_init.json:/ros2_ws/src/controller/config/tracking_init.json    
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}

  microros_agent:
    image: microros/micro-ros-agent:humble
    container_name: microros-agent
    network_mode: host
    privileged: true 
    volumes:
      - /dev:/dev
    command: "serial --dev /dev/ttyACM0"
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}