controller:
  ros__parameters:
    apf_gain: 0.4
    inter_agent_distance: 0.5
    tracked_frame_id: laser
    segments_topic: segments
    instructions_topic: instructions
    detected_objects_topic: detected_objects
    tracking_init_topic: tracking_init
    tracked_objects_topic: tracked_objects