controller:
  ros__parameters:
    alpha: 0.35
    deadzone: 0.1
    low_pass_filter_enabled: true
    deadzone_enabled: true
    apf_gain: 4.35
    inter_agent_distance: 0.5
    pid_p_gain: 0.05
    pid_i_gain: 0.0
    pid_d_gain: 0.0
    tracked_frame_id: laser
    segments_topic: segments
    instructions_topic: instructions
    detected_objects_topic: detected_objects
    tracking_init_topic: tracking_init
    tracked_objects_topic: tracked_objects
    odometry_topic: odom