controller:
  ros__parameters:
    alpha: 0.35
    deadzone_threshold: 0.5
    low_pass_filter_enabled: true
    deadzone_enabled: true
    apf_gain: 4.35
    inter_agent_distance: 0.5
    tracked_frame_id: laser
    segments_topic: segments
    instructions_topic: instructions
    detected_objects_topic: detected_objects
    tracking_init_topic: tracking_init
    tracked_objects_topic: tracked_objects